export const BRAND_NAME = "ALMO SEBASTIAN";

export const CATEGORY_WORDS = ["Skateboards,", "Apparel,", "Accessories"];
export const HERO_TERMINAL_PROMPT = "J3R3M3:$ ";
export const HERO_TERMINAL_TYPING_START_DELAY_MS = 500;
export const HERO_TERMINAL_TYPING_STEP_DURATION_MS = 52;
export const HERO_ENTER_TRANSITION_TRIGGER_SCROLL_PROGRESS = 0.12;
export const HERO_ENTER_WORDMARK_COMPLETION_DURATION = 0.56;
export const HERO_ENTER_TRANSITION_SCROLL_DELAY_MS = 980;
export const HERO_ENTER_TRANSITION_COMPLETE_DELAY_MS = 1760;

export const HERO_VIDEO_REVEAL_FALLBACK_DELAY_MS = 2600;
export const HERO_MEDIA_SETTLE_DURATION = 2.4;
export const HERO_OVERLAY_REVEAL_DELAY = 0.16;
export const HERO_OVERLAY_REVEAL_DURATION = 2.2;
export const HERO_CONTENT_REVEAL_DURATION = 1.8;
export const HERO_CONTENT_REVEAL_DELAY = 0.38;
export const HERO_VIDEO_FADE_OUT_PROGRESS = 0.6;
export const HERO_CONTENT_BLUR_AMOUNT = 10;
export const HERO_OVERLAY_COVER_PROGRESS = 0.16;
export const HERO_BLACK_PANEL_INITIAL_TOP_COVERAGE = 36;
export const HERO_BLACK_PANEL_INITIAL_BOTTOM_COVERAGE = 0;

export const DECAY_RATE = 0.18;
export const BASE_LIFT_DISTANCE = 360;
export const LETTER_STAGGER_DURATION = 0.032;
export const CATEGORY_WORD_ANIMATION_START_DELAY = 0.52;
export const CATEGORY_WORD_ANIMATION_STAGGER = 0.22;
export const CATEGORY_WORD_ANIMATION_DURATION = 0.32;
export const CATEGORY_ANIMATION_END_TIME =
  CATEGORY_WORD_ANIMATION_START_DELAY +
  (CATEGORY_WORDS.length - 1) * CATEGORY_WORD_ANIMATION_STAGGER +
  CATEGORY_WORD_ANIMATION_DURATION;
export const INTRO_BRAND_START_DELAY =
  (CATEGORY_WORD_ANIMATION_START_DELAY + CATEGORY_ANIMATION_END_TIME) / 2;
export const OUTRO_SCROLL_DISTANCE_FACTOR = 0.68;
export const MINIMUM_OUTRO_LIFT_VIEWPORT_FACTOR = 0.62;
export const CATEGORY_FADE_OUT_PROGRESS = 0.08;

export function getCategoryAnimationDelay(index) {
  return CATEGORY_WORD_ANIMATION_START_DELAY + index * CATEGORY_WORD_ANIMATION_STAGGER;
}

export function getMovementDistance(index) {
  const movementMultiplier = Math.exp(-DECAY_RATE * index);
  return BASE_LIFT_DISTANCE * movementMultiplier;
}

export function getInverseStaggerDelay(index, totalCharacters) {
  return INTRO_BRAND_START_DELAY + (totalCharacters - index - 1) * LETTER_STAGGER_DURATION;
}
